ci(macos-14): use gcc12 on macos-14, workaround is_recursive symbol missing (#1859)
With gcc 13.3+ (from brew) on ARM macs we get this

Undefined symbols for architecture arm64:
  "_is_recursive.16.0", referenced from:
      ___characterstringmodule_MOD_assign_to_charstring in libmf6core.a(Utilities_CharString.f90.o)
ld: symbol(s) not found for architecture arm64
collect2: error: ld returned 1 exit status

It reproduces locally. On inspection of the symbol table, _is_recursive.16.0 has type "U" (undefined) while there are several others with the same name and different index _is_recursive.N which have type "b" (local bss section symbol). Seems like a GCC bug? Maybe worth building from source and digging deeper, but that is not trivial. Falling back to gcc 12 for now.